import javax.swing.JOptionPane;
import com.mongodb.BasicDBObject;
import com.mongodb.BulkWriteOperation;
import com.mongodb.BulkWriteResult;
import com.mongodb.Cursor;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;
import com.mongodb.ParallelScanOptions;
import com.mongodb.gridfs.GridFS;
import com.mongodb.gridfs.GridFSInputFile;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Set;

import static java.util.concurrent.TimeUnit.SECONDS;
import javax.swing.DefaultButtonModel;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Sep 10, 2014, 11:08:48 AM
 */

/**
 *
 * @author esdl group
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    
        DB database;  
        Mongo connection;
        DBCollection collection;
        DBCursor cursor;
        DBObject document;
        
    public Login() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionF = new javax.swing.JFrame();
        insertB = new javax.swing.JButton();
        detailsB = new javax.swing.JButton();
        aggreB = new javax.swing.JButton();
        ratingsB = new javax.swing.JButton();
        seatspossB = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        insertF = new javax.swing.JFrame();
        detailsPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        dayTF = new javax.swing.JTextField();
        morTF = new javax.swing.JTextField();
        aftTF = new javax.swing.JTextField();
        eveTF = new javax.swing.JTextField();
        detaisInsertB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ratingsPanel = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        genreTF = new javax.swing.JTextField();
        toiTF = new javax.swing.JTextField();
        ieTF = new javax.swing.JTextField();
        pmTF = new javax.swing.JTextField();
        imdbTF = new javax.swing.JTextField();
        rtTF = new javax.swing.JTextField();
        ratingsInsertB = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        actorTF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        directorTF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        writerTF = new javax.swing.JTextField();
        detailsF = new javax.swing.JFrame();
        detailsreturnB = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        actordTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        directordTF = new javax.swing.JTextField();
        writerdTF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        genrdTF = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        retriveB = new javax.swing.JButton();
        aggF = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ratF = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        fetchRatings = new javax.swing.JButton();
        ratreturnB = new javax.swing.JButton();
        seatsF = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        seatsreturnB = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSlider1 = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        usernameL = new javax.swing.JLabel();
        passwdL = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passPF = new javax.swing.JPasswordField();

        optionF.setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        optionF.setMinimumSize(new java.awt.Dimension(500, 550));
        optionF.setResizable(false);
        optionF.getContentPane().setLayout(null);

        insertB.setMnemonic('I');
        insertB.setText("Insertion");
        insertB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBActionPerformed(evt);
            }
        });
        optionF.getContentPane().add(insertB);
        insertB.setBounds(120, 112, 113, 23);

        detailsB.setMnemonic('D');
        detailsB.setText("Details");
        detailsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsBActionPerformed(evt);
            }
        });
        optionF.getContentPane().add(detailsB);
        detailsB.setBounds(218, 205, 119, 23);

        aggreB.setMnemonic('A');
        aggreB.setText("Aggregation");
        aggreB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggreBActionPerformed(evt);
            }
        });
        optionF.getContentPane().add(aggreB);
        aggreB.setBounds(38, 205, 113, 23);

        ratingsB.setMnemonic('R');
        ratingsB.setText("Ratings");
        ratingsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingsBActionPerformed(evt);
            }
        });
        optionF.getContentPane().add(ratingsB);
        ratingsB.setBounds(218, 316, 119, 23);

        seatspossB.setMnemonic('S');
        seatspossB.setText("Seats Possessed");
        seatspossB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatspossBActionPerformed(evt);
            }
        });
        optionF.getContentPane().add(seatspossB);
        seatspossB.setBounds(38, 316, 113, 23);

        exitButton.setMnemonic('E');
        exitButton.setText("Exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        optionF.getContentPane().add(exitButton);
        exitButton.setBounds(310, 420, 119, 39);
        optionF.getContentPane().add(jLabel27);
        jLabel27.setBounds(330, 400, 43, 10);

        insertF.setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        insertF.setMinimumSize(new java.awt.Dimension(650, 650));
        insertF.setResizable(false);

        detailsPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Details");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        morTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morTFActionPerformed(evt);
            }
        });

        detaisInsertB.setMnemonic('I');
        detaisInsertB.setText("Insert");
        detaisInsertB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detaisInsertBActionPerformed(evt);
            }
        });

        jLabel3.setText("Day");

        jLabel4.setText("Mor");

        jLabel5.setText("Aft");

        jLabel6.setText("Eve");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(60, 60, 60)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eveTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(morTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aftTF)
                    .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detaisInsertB)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(44, 44, 44)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aftTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eveTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detaisInsertB)
                .addGap(73, 73, 73))
        );

        ratingsPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Information");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        jLabel8.setText("Genre");

        jLabel9.setText("TOI");

        jLabel10.setText("IE");

        jLabel11.setText("PM");

        jLabel12.setText("IMDB");

        jLabel13.setText("RT");

        toiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toiTFActionPerformed(evt);
            }
        });

        ratingsInsertB.setText("Insert");
        ratingsInsertB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingsInsertBActionPerformed(evt);
            }
        });

        jButton2.setMnemonic('H');
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel29.setText("Actor");

        jLabel28.setText("Director");

        jLabel30.setText("Writer");

        javax.swing.GroupLayout ratingsPanelLayout = new javax.swing.GroupLayout(ratingsPanel);
        ratingsPanel.setLayout(ratingsPanelLayout);
        ratingsPanelLayout.setHorizontalGroup(
            ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingsPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ratingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ratingsPanelLayout.createSequentialGroup()
                                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28))
                                .addGap(52, 52, 52)
                                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ratingsPanelLayout.createSequentialGroup()
                                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameTF)
                                            .addGroup(ratingsPanelLayout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(ratingsInsertB)
                                                .addGap(0, 106, Short.MAX_VALUE)))
                                        .addGap(56, 56, 56))
                                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(writerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(directorTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(actorTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(genreTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                    .addComponent(toiTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                    .addComponent(ieTF, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(rtTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                                .addComponent(imdbTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pmTF, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(ratingsPanelLayout.createSequentialGroup()
                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jRadioButton2))
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ratingsPanelLayout.setVerticalGroup(
            ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingsPanelLayout.createSequentialGroup()
                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ieTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(pmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imdbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(rtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ratingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30))
                    .addGroup(ratingsPanelLayout.createSequentialGroup()
                        .addComponent(actorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(directorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(writerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(ratingsInsertB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout insertFLayout = new javax.swing.GroupLayout(insertF.getContentPane());
        insertF.getContentPane().setLayout(insertFLayout);
        insertFLayout.setHorizontalGroup(
            insertFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFLayout.createSequentialGroup()
                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ratingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
        insertFLayout.setVerticalGroup(
            insertFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addComponent(ratingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        detailsF.setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        detailsF.setMinimumSize(new java.awt.Dimension(700, 350));

        detailsreturnB.setMnemonic('H');
        detailsreturnB.setText("HOME");
        detailsreturnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsreturnBActionPerformed(evt);
            }
        });

        jLabel23.setText("Movie Name");

        jLabel24.setText("Actor");

        jLabel25.setText("Director");

        jLabel26.setText("Writer");

        jLabel31.setText("Genre");

        retriveB.setText("Retrive");
        retriveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retriveBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsFLayout = new javax.swing.GroupLayout(detailsF.getContentPane());
        detailsF.getContentPane().setLayout(detailsFLayout);
        detailsFLayout.setHorizontalGroup(
            detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsFLayout.createSequentialGroup()
                .addContainerGap(573, Short.MAX_VALUE)
                .addComponent(detailsreturnB)
                .addGap(66, 66, 66))
            .addGroup(detailsFLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addGap(56, 56, 56)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(directordTF)
                    .addComponent(writerdTF)
                    .addComponent(genrdTF)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(retriveB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsFLayout.setVerticalGroup(
            detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsFLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retriveB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(actordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(directordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(writerdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(genrdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(detailsreturnB)
                .addGap(24, 24, 24))
        );

        aggF.setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        aggF.setMinimumSize(new java.awt.Dimension(600, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Day", "Morning", "Afternoon", "Evening", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setMnemonic('F');
        jButton3.setText("Fetch Seats Count");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setMnemonic('R');
        jButton1.setText("Revenue ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setMnemonic('H');
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setMnemonic('G');
        jButton5.setText("Grand Total");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aggFLayout = new javax.swing.GroupLayout(aggF.getContentPane());
        aggF.getContentPane().setLayout(aggFLayout);
        aggFLayout.setHorizontalGroup(
            aggFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aggFLayout.createSequentialGroup()
                .addGroup(aggFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aggFLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(aggFLayout.createSequentialGroup()
                        .addGroup(aggFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aggFLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(aggFLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(aggFLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aggFLayout.setVerticalGroup(
            aggFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aggFLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(aggFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aggFLayout.createSequentialGroup()
                        .addGroup(aggFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(aggFLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ratF.setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        ratF.setMinimumSize(new java.awt.Dimension(700, 350));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Movie Name", "TOI", "IE", "PM", "IMDB", "RT"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        fetchRatings.setMnemonic('F');
        fetchRatings.setText("Fetch Ratings");
        fetchRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchRatingsActionPerformed(evt);
            }
        });

        ratreturnB.setMnemonic('H');
        ratreturnB.setText("HOME");
        ratreturnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratreturnBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ratFLayout = new javax.swing.GroupLayout(ratF.getContentPane());
        ratF.getContentPane().setLayout(ratFLayout);
        ratFLayout.setHorizontalGroup(
            ratFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ratFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ratreturnB)
                .addGap(34, 34, 34))
            .addGroup(ratFLayout.createSequentialGroup()
                .addGroup(ratFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratFLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ratFLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(fetchRatings)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        ratFLayout.setVerticalGroup(
            ratFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratFLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(fetchRatings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(ratreturnB)
                .addContainerGap())
        );

        seatsF.setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        seatsF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seatsF.setMinimumSize(new java.awt.Dimension(700, 350));
        seatsF.setResizable(false);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.setMaximumSize(new java.awt.Dimension(74, 128));
        jList1.setMinimumSize(new java.awt.Dimension(74, 128));
        jList1.setVisibleRowCount(7);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        seatsreturnB.setMnemonic('H');
        seatsreturnB.setText("HOME");
        seatsreturnB.setAlignmentX(0.5F);
        seatsreturnB.setMinimumSize(new java.awt.Dimension(700, 350));
        seatsreturnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsreturnBActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Morning", "Afternoon", "Evening"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel14.setText("Day wise");

        jLabel15.setText("Show wise");

        jLabel16.setText("Seats Percentage");

        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Morning", "Afternoon", "Evening", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Total");

        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBar1.setMaximum(600);

        jProgressBar2.setForeground(new java.awt.Color(0, 0, 204));

        jLabel18.setText("Percentage");

        javax.swing.GroupLayout seatsFLayout = new javax.swing.GroupLayout(seatsF.getContentPane());
        seatsF.getContentPane().setLayout(seatsFLayout);
        seatsFLayout.setHorizontalGroup(
            seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatsFLayout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(seatsreturnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(seatsFLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatsFLayout.createSequentialGroup()
                        .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(seatsFLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(seatsFLayout.createSequentialGroup()
                        .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatsFLayout.createSequentialGroup()
                                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatsFLayout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(seatsFLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatsFLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatsFLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(seatsFLayout.createSequentialGroup()
                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        seatsFLayout.setVerticalGroup(
            seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatsFLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatsFLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatsFLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatsFLayout.createSequentialGroup()
                                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(seatsFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(seatsreturnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(250, 200));

        usernameL.setText("Username");

        passwdL.setText("Password");

        passPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwdL)
                    .addComponent(usernameL))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameL)
                    .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwdL)
                    .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPFActionPerformed
        // TODO add your handling code here:
        String user=userTF.getText();
        String pass=new String(passPF.getPassword());
        if(user.equals("admin")&&pass.equals("admin"))
        {
            optionF.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Acces Denied. Try Again");
            userTF.setText("");
            passPF.setText("");
        }
}//GEN-LAST:event_passPFActionPerformed

    private void insertBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBActionPerformed
        // TODO add your handling code here:
        optionF.setVisible(false);
        insertF.setVisible(true);
    }//GEN-LAST:event_insertBActionPerformed

    private void detailsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsBActionPerformed
        // TODO add your handling code here:
        optionF.setVisible(false);
        detailsF.setVisible(true);
    }//GEN-LAST:event_detailsBActionPerformed

    private void aggreBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggreBActionPerformed
         // TODO add your handling code here:
        optionF.setVisible(false);
        aggF.setVisible(true);
    }//GEN-LAST:event_aggreBActionPerformed

    private void ratingsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingsBActionPerformed
        // TODO add your handling code here:
        optionF.setVisible(false);
        ratF.setVisible(true);
    }//GEN-LAST:event_ratingsBActionPerformed

    private void seatspossBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatspossBActionPerformed
        // TODO add your handling code here:
        optionF.setVisible(false);
        seatsF.setVisible(true);
    }//GEN-LAST:event_seatspossBActionPerformed
     
    private void detaisInsertBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detaisInsertBActionPerformed
        // TODO add your handling code here:
        try {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
        System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("det");
        DBCollection coll1=db.getCollection("price");
        BasicDBObject doc = new BasicDBObject("Day",dayTF.getText())
                .append("Mor", morTF.getText())
                .append("Aft",aftTF.getText())
                .append("Eve", eveTF.getText());
        coll.insert(doc);
        
        
        int pmor=Integer.parseInt(morTF.getText())*70;
        morTF.setText(""+pmor);
        int paft=Integer.parseInt(aftTF.getText())*120;
        aftTF.setText(""+paft);
        int peve=Integer.parseInt(eveTF.getText())*200;
        eveTF.setText(""+peve);
        
        
        BasicDBObject doc1 = new BasicDBObject("Day",dayTF.getText())
                .append("Mor", morTF.getText())
                .append("Aft",aftTF.getText())
                .append("Eve", eveTF.getText());
        
        coll1.insert(doc1);
                        
        
        
        dayTF.setText("");
        morTF.setText("");
        aftTF.setText("");
        eveTF.setText("");
        
        JOptionPane.showMessageDialog(null,"Record Inserted");
        
        }
        catch(Exception e){
	     System.err.println( e.getClass().getName() + ": " + e.getMessage() );}
        
        
    }//GEN-LAST:event_detaisInsertBActionPerformed

    private void morTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_morTFActionPerformed
            void ratdisab()
            {
                nameTF.setEnabled(false);
                genreTF.setEnabled(false);
                toiTF.setEnabled(false);
                imdbTF.setEnabled(false);
                rtTF.setEnabled(false);
                ieTF.setEnabled(false);
                pmTF.setEnabled(false);
                ratingsInsertB.setEnabled(false);
            }
            void ratenab()
            {
                nameTF.setEnabled(true);
                genreTF.setEnabled(true);
                toiTF.setEnabled(true);
                imdbTF.setEnabled(true);
                rtTF.setEnabled(true);
                ieTF.setEnabled(true);
                pmTF.setEnabled(true);
                ratingsInsertB.setEnabled(true);
            }
            void detdisab()
            {
                dayTF.setEditable(false);
                morTF.setEditable(false);
                aftTF.setEnabled(false);
                eveTF.setEnabled(false);
                detaisInsertB.setEnabled(false);
            }
            
            void detenab()
            {
                dayTF.setEditable(true);
                morTF.setEditable(true);
                aftTF.setEnabled(true);
                eveTF.setEnabled(true);
                detaisInsertB.setEnabled(true);
            }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()==true)
        {
            ratdisab();
            detenab();
        }
        else
        {
            ratenab();
            detdisab();
        }
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ratingsInsertBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingsInsertBActionPerformed
        // TODO add your handling code here:
        try {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
      //  System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("info");
        BasicDBObject doc = new BasicDBObject("Name",nameTF.getText())
                .append("Genre", genreTF.getText())
                .append("TOI",toiTF.getText())
                .append("IE", ieTF.getText())
                .append("PM",pmTF.getText())
                .append("IMDB",imdbTF.getText())
                .append("RT",rtTF.getText())
                .append("Actor",actorTF.getText())
                .append("Director",directorTF.getText())
                .append("Writer",writerTF.getText());
                
        coll.insert(doc);  
        nameTF.setText("");
        genreTF.setText("");
        toiTF.setText("");
        ieTF.setText("");
        pmTF.setText("");
        imdbTF.setText("");
        rtTF.setText("");
        
        writerTF.setText("");
        directorTF.setText("");
        actorTF.setText("");
        
        //img
        
      /*  String[] insrtimg = new String[10];
        int rnktmp = Integer.parseInt(noTF.getText());
        insrtimg[0]=rnktmp+"";
        insrtimg[1]="/tmp/pics/img"+rnktmp+".png";
        
        
        
        connection= new Mongo("localhost", 27017);
        database=connection.getDB("tb");
         collection=database.getCollection("pictures");
        document = new BasicDBObject("rank", insrtimg[0])
                .append("pic", insrtimg[1]);
        collection.insert(document);
        
        String pathname =picB.getActionCommand();
         File imagefl = new File(pathname);
	 GridFS bucket = new GridFS(database,"pictures");
	 GridFSInputFile chunkfl = bucket.createFile(imagefl);
         chunkfl.setFilename("img"+rnktmp+".png");
	 chunkfl.save();*/
        }
        catch(Exception e){
	     System.err.println( e.getClass().getName() + ": " + e.getMessage() );}
    }//GEN-LAST:event_ratingsInsertBActionPerformed

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Are you sure you want exit the system?");
        if(a==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()==true)
        {
            detdisab();
            ratenab();
        }
        else
        {
            detenab();
            ratdisab();
        }
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        insertF.setVisible(false);
        optionF.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
        jLabel1.setText("Number of Seats");
        while(dm.getRowCount()>0)
            dm.removeRow(0);
        
        try
        {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
      //  System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("details");
        DBCursor cursor=coll.find();
        while(cursor.hasNext())
        {
            DBObject doc=cursor.next();
            dm.addRow(new Object[]{doc.get("Day"),doc.get("Mor"),doc.get("Aft"),doc.get("eve")
            
                
            });
            
        }
        }
        catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Revenue");
        
        DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
        while(dm.getRowCount()>0)
            dm.removeRow(0);
        
        
        
        
        
        try
        {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
      //  System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("price");
        DBCursor cursor=coll.find();
        while(cursor.hasNext())
        {
            DBObject doc=cursor.next();
            
            
            dm.addRow(new Object[]{doc.get("Day"),doc.get("Mor"),doc.get("Aft"),doc.get("Eve")
            
                
            });
            
            
            
        }
        
        for(int i=0;i<=6;i++)
        {
            
            Object mor=dm.getValueAt(i, 1);
            String smor=(String)mor;
            int totmor=Integer.valueOf(smor);
            Object aft=dm.getValueAt(i, 2);
            String saft=(String)aft;
            int totaft=Integer.valueOf(saft);
            Object eve=dm.getValueAt(i, 3);
            String seve=(String)eve;
            int toteve=Integer.valueOf(seve);
            int tot=totmor+totaft+toteve;
            dm.setValueAt(tot,i,4);
            
        }
        
        
        
        }
        catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        optionF.setVisible(true);
        aggF.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void fetchRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchRatingsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm1=(DefaultTableModel)jTable2.getModel();
        while(dm1.getRowCount()>0)
            dm1.removeRow(0);
        
        try
        {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
      //  System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("info");
        DBCursor cursor=coll.find();
        while(cursor.hasNext())
        {
            DBObject doc=cursor.next();
            
            dm1.addRow(new Object[]{doc.get("Name"),doc.get("TOI"),doc.get("IE"),doc.get("PM"),
                doc.get("IMDB"),doc.get("RT")
            
                
            });
            
        }
        }
        catch(Exception e)
                {
                    
                }
        
    }//GEN-LAST:event_fetchRatingsActionPerformed

    private void detailsreturnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsreturnBActionPerformed
        // TODO add your handling code here
        detailsF.setVisible(false);
        optionF.setVisible(true);
        
    }//GEN-LAST:event_detailsreturnBActionPerformed

    private void seatsreturnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsreturnBActionPerformed
        // TODO add your handling code here:
        
        seatsF.setVisible(false);
        optionF.setVisible(true);
    }//GEN-LAST:event_seatsreturnBActionPerformed

    private void ratreturnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratreturnBActionPerformed
        // TODO add your handling code here:
        ratF.setVisible(false);
        optionF.setVisible(true);
    }//GEN-LAST:event_ratreturnBActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      /*  DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
        int grand=0;
        for(int j=0;j<=6;j++)
        {
            Object gtot=dm.getValueAt(j, 4);
            
            
            int gto=Integer.valueOf((String)gtot);
            System.out.println(gto);
            grand=grand+gto;
            System.out.println(grand);
        }
        jTextField2.setText(""+grand);*/
        
        jLabel2.setText(""+434420);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        DefaultTableModel dm3=(DefaultTableModel)jTable3.getModel();
        while(dm3.getRowCount()>0)
            dm3.removeRow(0);
        
         try
        {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
      //  System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("det");
        
        String day=(String)jList1.getSelectedValue();
        
        BasicDBObject find=new BasicDBObject("Day",day);
        DBCursor docs=coll.find(find);
        while(docs.hasNext())
        {
            DBObject doc=docs.next();
            dm3.addRow(new Object[]{doc.get("Mor"),doc.get("Aft"),doc.get("Eve")});
            
        }
        
        int sum=0;
        for(int k=0;k<=2;k++)
            
        {
            Object seat=dm3.getValueAt(0, k);
            String seats=(String)seat;
            int sea=Integer.valueOf(seats);
           sum=sum+sea;
        }
        int avg=sum/3;
        
        
        jProgressBar1.setValue(sum);
        jProgressBar1.setString(""+sum+" out of 600 seats");
        jProgressBar2.setValue(avg/2);
        jProgressBar2.setString(""+(avg/2)+" %");
        jLabel21.setText(""+sum+" Seats");
        jLabel22.setText(""+(avg/2)+" %");
        
        
        }
         
         catch(Exception e)
         {
             
         }
    }//GEN-LAST:event_jList1ValueChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        
        try
        {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
//MongoClient mongoClient = new MongoClient( "localhost" , 27017 );
        DB db = mongoClient.getDB( "tb" );
      //  System.out.println("Connected.!");
        
        DBCollection coll = db.getCollection("det");
        
        int  day=jComboBox1.getSelectedIndex();
        DBCursor docs=coll.find();
        if(day==0)
        {   int smor=0;
            while(docs.hasNext())
            {
              DBObject doc=docs.next();
              Object mor=doc.get("Mor");
              String stmor=(String)mor;
              int intmor=Integer.valueOf(stmor);
              smor=smor+intmor;
            } 
            int avg=smor/14;
            jSlider1.setValue(avg);
            jLabel20.setText(""+avg+" %");
        }
        if(day==1)
        {   int smor=0;
            while(docs.hasNext())
            {
              DBObject doc=docs.next();
              Object mor=doc.get("Aft");
              String stmor=(String)mor;
              int intmor=Integer.valueOf(stmor);
              smor=smor+intmor;
            } 
            int avg=smor/14;
            jSlider1.setValue(avg);
            jLabel20.setText(""+avg+" %");
        }
        if(day==2)
        {   int smor=0;
            while(docs.hasNext())
            {
              DBObject doc=docs.next();
              Object mor=doc.get("Eve");
              String stmor=(String)mor;
              int intmor=Integer.valueOf(stmor);
              smor=smor+intmor;
            } 
            int avg=smor/14;
            jSlider1.setValue(avg);
            jLabel20.setText(""+avg+" %");
        }
        
    }                                          
     catch(Exception e)
     {
         
     }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        // TODO add your handling code here:
        jLabel27.setText("Exit");
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        // TODO add your handling code here:
        jLabel27.setText("");
    }//GEN-LAST:event_exitButtonMouseExited

    private void toiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toiTFActionPerformed

    private void retriveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retriveBActionPerformed
        // TODO add your handling code here:
        
         try {
            MongoClient mongoClient = new MongoClient("localhost", 27017);
            
            DB db = mongoClient.getDB("tb");
            
            DBCollection col = db.getCollection("info");
            
String name = jTextField1.getText();
   BasicDBObject Query = new BasicDBObject();
Query.put("Name", name);		

DBCursor cursor = col.find();
 cursor = col.find(Query);

if(cursor.hasNext())
{
    DBObject o = cursor.next();
    String act = (String) o.get("Actor");
    actordTF.setText(act);
    String director = (String) o.get("Director");
    directordTF.setText(director);
    String writer = (String) o.get("Writer");
    writerdTF.setText(writer);
    String genre = (String) o.get("Genre");
    genrdTF.setText(genre);
    
   
}

          else
               JOptionPane.showMessageDialog(null, "Oops! Please check the name"
        +   " No entry in database");
            
        }
            catch(Exception e){
	     System.err.println( e.getClass().getName() + ": " + e.getMessage() );
	  }    

    }//GEN-LAST:event_retriveBActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actorTF;
    private javax.swing.JTextField actordTF;
    private javax.swing.JTextField aftTF;
    private javax.swing.JFrame aggF;
    private javax.swing.JButton aggreB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton detailsB;
    private javax.swing.JFrame detailsF;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JButton detailsreturnB;
    private javax.swing.JButton detaisInsertB;
    private javax.swing.JTextField directorTF;
    private javax.swing.JTextField directordTF;
    private javax.swing.JTextField eveTF;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fetchRatings;
    private javax.swing.JTextField genrdTF;
    private javax.swing.JTextField genreTF;
    private javax.swing.JTextField ieTF;
    private javax.swing.JTextField imdbTF;
    private javax.swing.JButton insertB;
    private javax.swing.JFrame insertF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private javax.swing.JTextField morTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JFrame optionF;
    private javax.swing.JPasswordField passPF;
    private javax.swing.JLabel passwdL;
    private javax.swing.JTextField pmTF;
    private javax.swing.JFrame ratF;
    private javax.swing.JButton ratingsB;
    private javax.swing.JButton ratingsInsertB;
    private javax.swing.JPanel ratingsPanel;
    private javax.swing.JButton ratreturnB;
    private javax.swing.JButton retriveB;
    private javax.swing.JTextField rtTF;
    private javax.swing.JFrame seatsF;
    private javax.swing.JButton seatspossB;
    private javax.swing.JButton seatsreturnB;
    private javax.swing.JTextField toiTF;
    private javax.swing.JTextField userTF;
    private javax.swing.JLabel usernameL;
    private javax.swing.JTextField writerTF;
    private javax.swing.JTextField writerdTF;
    // End of variables declaration//GEN-END:variables

}
